### ISSUE TITLE
Cann't achieve high performance as listed in your paper.

### ISSUE THREAD

**Issue by Jianlou** [VisualComputingInstitute/triplet-reid#2]
Hi,
I carefully follow your paper, using a pre-trained ResNet50 and hard triplets mining in my implementation. And only got rank1 73% and map 54%.  I have adjust many different hyper-parameters, and still cann't achieve the high performance as listed in your paper. 

Is there any implementation details or tricks should I consider in my experiments?

Thanks.

**Comment by qw87494512** [comment]
can you share you code?

**Comment by Pandoro** [comment]
Hi there,

Thank you for your interest in our paper. We tried to be very complete during writing the paper and all the important things are in the paper. Given that it is very hard to estimate what you are doing different right now, it is hard to suggest any specific details. However, you do say you have been adjusting hyper-parameters. What kind of hyper-parameters do you mean? I would say that (almost?) all of the important hyper-paramters have been specified in the paper, I can't say what happens if you change them.

**Comment by delip** [comment]
Just adding to list of requesters. Would love to see your implementation for reference.

**Comment by lucasb-eyer** [comment]
It's coming soon. Sorry, we're both too busy with internships, but open-sourcing the full training code will be the first thing we do when we get back to the lab, expected end-September!

During our experiments, performance was relatively robust to many small changes (say +- 3% mAP roughly), so I'm also looking forward to learning why your code fails.

**Comment by lucasb-eyer** [comment]
Hi all, sorry for the permanent delay, that was terribly handled by us, but oh well, real life :)

We just pushed clean training code that is hopefully simple to use and does reproduce the performance from the paper. It's still missing embedding and evaluation code, which we're cleaning up and will commit too, soon.

Closing this issue.
