### ISSUE TITLE
Code does not utilize GPU

### ISSUE THREAD

**Issue by pasxalinamed** [VisualComputingInstitute/triplet-reid#3]
After running your code I noticed that it does not run in GPU even after  asking it explicitly with THEANO_FLAGS=device=cuda0 python trinet_embed.py

Could you please explain why this happens?
Thank you

**Comment by lucasb-eyer** [comment]
Follow the [Theano documentation about GPU](http://deeplearning.net/software/theano_versions/dev/tutorial/using_gpu.html) closely. In this case, it's probably because you forgot to also set `floatX=float32`.

I'm closing as this should solve it and it's probably not an issue with our code, but if you disagree, feel free to re-open.
