### ISSUE TITLE
Performance on different dataset not good

### ISSUE THREAD

**Issue by SmitSheth** [VisualComputingInstitute/triplet-reid#59]
Hello,
I used the pre-trained model given in this repository on my own image dataset to calculate embeddings and then calculated eucledian distance between the embeddings. Testing on same person with different view, postures, gives bad result(eucledian distance is high for some images and low for some).  Link to sample images of a person i tested on https://drive.google.com/open?id=15QKkosOP6sRFB8xzJz8O36OXEvEfegeI. 

NOTE:
I have used the pre-trained model given.

**Comment by Pandoro** [comment]
Sadly the model is not super robust to such variants because they did not appear in the training data. While the framework itself is by no means the issue here, you will need to gather additional training data, or create a mix of multiple datasets in order to train a more general model that might be robust to such inputs.

We will likely not be doing such a thing in in the near future. So I'll close this issue. If you train such a model and have additional results or questions feel free to re-open it.
