### ISSUE TITLE
Do you have any comparison on performance of model with/o embedding normalization 

### ISSUE THREAD

**Issue by voqtuyen** [VisualComputingInstitute/triplet-reid#67]

**Comment by Pandoro** [comment]
We don't have any hard numbers right now. I'm sure we did experiments and as far as I recall there wasn't a major difference. Hence we used the simpler version without the normalization. Especially since we also worked on the MARS dataset, where we need to average embeddings and there it isn't completely obvious how to best do this when the embeddings are normalized.

It should be very easy to try this though. If you do it, it would be great if you can report some numbers.

**Comment by voqtuyen** [comment]
@Pandoro Thanks
