### ISSUE TITLE
Retraining on ssd_mobilenet_v2_coco

### ISSUE THREAD

**Issue by ahmedfadhil** [VisualComputingInstitute/triplet-reid#80]
Thank you for the repository. 
I would like to ask if it is possible to retrain on ssd_mobilenet_v2_coco, and what params I must tweak to get started.
Thank you

**Comment by Pandoro** [comment]
Hi there!

I guess that, given the "ssd" in the model name, you are referring to a detector. This might be possible, but it is definitely nothing that is supported by our code. Depending on how you would add the person embedding into the detector, after fine-tuning the model with the ReID task, there is no guarantee that the detector will still work properly. Training such a model for detection and ReID jointly using the batch hard loss is rather complicated too though, given the batch composition for both tasks is very different.

I'm quite sure there are some papers out there that have added a ReID module into a detector, but this is likely easier for two stage detectors such as Faster RCNN and the likes or by using a different loss for the ReID. It would probably be a good idea to look at such papers.

Since there isn't a lot more advice that I can give on this topic, and it's somewhat off-topic, I'll close this issue. Feel free to comment with more questions though.
