### ISSUE TITLE
hard triplet loss

### ISSUE THREAD

**Issue by ffredd** [VisualComputingInstitute/triplet-reid#96]
I use triple loss between data of two modalities to reduce the distance between different modalities of the same class and increase the distance between different modalities  of different class. But when I use batch_all loss, the valid set loss has not changed; now using hard_loss, the valid set loss still has not changed. What is the reason? I found some answers that triplet is difficult to converge. What do you do to deal with triplet loss convergence?

**Comment by Pandoro** [comment]
Dear ffredd,

This is sadly a very off-topic question, since this repo is only concerned with the triplet loss for person re-identification and we will not be able to give you support on a rather orthogonal project. I'm not even sure what you mean with  the "valid set loss". If your loss does not change at all though, I would guess there is a bug in your code. We discuss the convergence of the triplet loss at length in our paper, so feel free to have a look at that.

Closing this issue.

**Comment by ffredd** [comment]
> Dear ffredd,
> 
> This is sadly a very off-topic question, since this repo is only concerned with the triplet loss for person re-identification and we will not be able to give you support on a rather orthogonal project. I'm not even sure what you mean with the "valid set loss". If your loss does not change at all though, I would guess there is a bug in your code. We discuss the convergence of the triplet loss at length in our paper, so feel free to have a look at that.
> 
> Closing this issue.

I'm sorry I misspelled the word ‘validation set’, and I'm looking for errors, thank you again for your reply！
